### ISSUE TITLE
Adding the language switcher to all pages adds one for user accounts

### ISSUE THREAD

**Issue by terzag** [picasso/zu-translate#3]
I've just noticed another bug when fiddling with WC but it's not (really) related to it: when editing customers account from WooCommerce → Customers → clicking on one will open the user-edit.php?user_id=xxx, which is actually the user edit page from WP. When the "Add language switcher to all pages/posts" option from Zu Translate is enabled, there'll be a switcher on that user edit page that just does nothing (which is expected I guess, as it's a WP settings page).

The only thing related to WC is that if you edit your own admin account as a customer, it'll send you to the profile page but with the user-edit one (i.e. it'll be user-edit.php?user_id=1) instead of profile.php; on the profile.php page, the language switcher does not appear.

When disabling Zu Translate, qTranslate-XT doesn't add a language switcher to the user-edit page (nor profile.php). I'm not sure if it's a matter of excluding a specific cpt (I'm not sure which one is used: adding user_id to the list of exclusions doesn't work) or if the "Add language switcher" option should exclude a list of pages (as it'll display also on various settings pages and I'm not sure it's intended).

**Comment by picasso** [comment]
From where users are appear in the store? How can I add someone to testing?

**Comment by terzag** [comment]
I'd say: don't bother with the WC part. The issue is mostly related to WP (the only specific stuff from WC is that it'll let you edit the admin account through the user-edit.php page instead of the profile.php page), that's why I opened a different report.

When enabling the language switcher on all post/pages, it's displayed on some settings page, like options-general.php and user-edit.php. But it isn't displayed on other settings pages, like options-writing.php and such. I'm not sure which is the expected case:
- should the language switcher appear on settings pages?
- or shouldn't it, in which case, regarding users, it does not appear on profile.php but appears on user-edit.php, which leads to some confusion as user-edit.php?user_id=1 and profile.php edit the same content but one page shows the language switcher and the other doesn't.

IMO, it shouldn't appear on settings pages, as their content is not really supposed to be translatable.

**Comment by picasso** [comment]
option `Add "Language Switcher" to post/pages list` is responsible for adding the language switcher on pages that have `edit.php` in its URL. Therefore, the switchers on all other pages (`profile.php`, `options-general.php` etc) is the job __qTranslate-XT__.

> should the language switcher appear on settings pages?

Yes, but only if there are fields for translation. On the `options-writing.php` page there are simply no such fields.

> it shouldn't appear on settings pages, as their content is not really supposed to be translatable.

On the `options-general.php ` page there are 2 fields for translation.

**Comment by terzag** [comment]
Ok, I messed up my tests, the language switcher on options-general.php is indeed added by qTranslate-XT.

But the switcher added on user-edit.php is from Zu Translate and I'm not sure it's a good idea to add it there, as there are credential fields.

**Comment by picasso** [comment]
Try version `1.3.5`

**Comment by terzag** [comment]
Tried version 1.3.5 and and despite enabling the switcher on all posts/pages, I don't have it anymore on the users accounts pages.

Seems fine to me.
